repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
        args:
          - --redact=100
  - repo: local
    hooks:
      - id: shellcheck-bootstrap-scripts
        name: shellcheck bootstrap scripts
        entry: shellcheck
        language: system
        files: ^bootstrap/scripts/.*\.sh$
        args:
          - -x
